version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: my_postgres
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./internal/database:/docker-entrypoint-initdb.d

volumes:
    db_data:
